### ISSUE TITLE
Why so many broken stuff with the latest version?

### ISSUE THREAD

**Issue by sanebg** [IAHispano/Applio#224] opened 2024-01-22 02:22 UTC
**Describe the bug**
While the new version have a nicer UI and colors, a lot of stuff is broken. 

For example - the record button is hidden behind the UI and it's hard to be accessed. 

No RMVPE +GPU option for pitch extraction (only RMVPE)

No settings page - no way to change the theme of the UI.

SIGNIFICANTLY slower generation on RTX 4090 (in the previous version before the UI update same thing was generated for 3 seconds, now it's 11 seconds)

It feels like an upgrade and downgrade at the same time. :/

**Comment by blaise-tk** [comment] 2024-01-22 05:56
I don't understand the point of your comment.

It was said several times that the new version would be released with less important features like changing a theme, because yes, it's not a priority, and you know what the problem is? That many themes are outdated and it's not that easy.

What you say about the screen recorder I don't understand what you mean, it's a normal button, and rmvpe gpu no longer worked in the previous version.

Nobody forces you to use this version, if you want to wait a few weeks for more features I don't care, the version change makes it easier for us to improve applio more constantly.

**Closed by blaise-tk** 2024-01-22 05:56 UTC

**Comment by blaise-tk** [comment] 2024-01-22 05:58
![IMG_2327](https://github.com/IAHispano/Applio/assets/133521603/a45a0bfc-9cd3-49e3-910f-b61a51145f80)

**Comment by sanebg** [comment] 2024-01-23 06:55
![image](https://github.com/IAHispano/Applio/assets/71310787/6b1c794f-fabc-491f-b091-0c3190d4a0f7) here is the recording button, hidden below the select audio layer (tested on different resolutions and scales)

Also as I said the generation of audio is SIGNIFICANTLY slower than he previous versions. Though this was feedback but obviously it was not welcomed, whatever, good luck.

**Comment by sanebg** [comment] 2024-01-24 07:59
Just to let you know the  precompiled link is the one of the older version instead of the new one (3.0.3 instead of the 3.0.4) in the releases page :)
