### ISSUE TITLE
[Bug]: Can't install ffmpeg on Fedora

### ISSUE THREAD

**Issue by kro-ai** [IAHispano/Applio#781] opened 2024-10-04 16:00 UTC
### Project Version

Latest version

### Platform and OS Version

Nobara 40 (Fedora)

### Affected Devices

Linux

### What happened?

I've been using Applio on Linux with no issues, but  I recently updated my machine and decided to re-install Applio, but right after clicking install-applio.sh, but almost immediately it gives an error "Unsupported distribution for FFmpeg installation." I'm not sure If you guys updated ffmpeg to another version or what, but It has broken the install on Linux.

### Steps to reproduce

1. Try to install
2. Error

### Expected behavior

I expect it to install properly.

**Comment by aris-py** [comment] 2024-10-04 16:44
I will fix it, this happens because in Fedora there is no package manager like “apt” or “pacman”, it is fixed by adding zipper and dnf.

**Comment by aris-py** [comment] 2024-10-04 16:46
Of course, if I remove the package managers, ffmpeg would not install or some audio formats would fail.

**Comment by kro-ai** [comment] 2024-10-04 17:08
@aris-py Ah okay! that makes sense

**Comment by aris-py** [comment] 2024-10-04 17:09
I saw what the problem is, it's the Fedora repositories which don't have the FFmpeg package, I have a solution for you:
- Enable RPM Fusion: Run these commands to enable the RPM Fusion repositories (both free and non-free version):
`sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
`
- Then install ffmpeg with this command: `sudo dnf install ffmpeg ffmpeg-libs
`
- And finally verify the installation of ffmpeg with `ffmpeg --version`.

**Comment by kro-ai** [comment] 2024-10-04 17:19
I'm on Nobara, and It already has ffmpeg pre-installed, I tried "sudo dnf install ffmpeg ffmpeg-libs" and it gave an error because of that. Which is why It's really strange that Applio won't install. It's ffmpeg-free.

**Comment by aris-py** [comment] 2024-10-04 17:21
I'm testing my fix in Fedora and I see that it works, if everything goes well I'll make a pr to fix it.

**Comment by kro-ai** [comment] 2024-10-04 17:22
@aris-py I appreciate it!

**Comment by aris-py** [comment] 2024-10-04 17:31
You can test my fix through my Applio fork where I test to see if everything works correctly.
https://github.com/aris-py/ApplioLinux

**Comment by kro-ai** [comment] 2024-10-04 17:41
Unfortunately It didn't work, now It says "Unsupported package manager for installing ffmpeg."

**Comment by aris-py** [comment] 2024-10-04 17:47
I will try FlatPack

**Comment by kro-ai** [comment] 2024-10-04 20:33
Alright

**Comment by aris-py** [comment] 2024-10-05 06:14
I just installed Nobara Linux for better testing

**Comment by kro-ai** [comment] 2024-10-05 08:37
I'm just wondering what has changed, because I've used Applio on Nobara without issue before.. Really strange

**Comment by kro-ai** [comment] 2024-10-05 13:50
@aris-py I saw you had pushed a few updates so I gave your repo another try, and It looks like It's working! So whatever change you pushed seems to have fixed it.

**Closed** 2024-10-05 20:34 UTC
Labels: bug
