### ISSUE TITLE
[BUG] Inference error

### ISSUE THREAD

**Issue by MarcoReckless** [IAHispano/Applio#214] opened 2024-01-20 20:32 UTC
**Describe the bug**
When trying to use inference to create a cover, the program fails to save the output.

**Expected behavior**
Before the upgrade to 3.0, inference worked as usual.

**Assets**
`Split all chunks for C:\RVC\Applio-RVC-Fork\assets\audios\v.wav successfully!
zero-size array to reduction operation maximum which has no identity
cannot unpack non-iterable NoneType object
Conversion completed. Output file: 'C:\RVC\Applio-RVC-Fork\assets\audios\v_output.wav'
Traceback (most recent call last): File "C:\RVC\Applio-RVC-Fork\env\lib\site-packages\gradio\queueing.py", line 495, in call_prediction output = await route_utils.call_process_api( File 
"C:\RVC\Applio-RVC-Fork\env\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api output = await app.get_blocks().process_api( File 
"C:\RVC\Applio-RVC-Fork\env\lib\site-packages\gradio\blocks.py", line 1570, in process_api data = self.postprocess_data(fn_index, result["prediction"], state) File 
"C:\RVC\Applio-RVC-Fork\env\lib\site-packages\gradio\blocks.py", line 1456, in postprocess_data outputs_cached = processing_utils.move_files_to_cache( File 
"C:\RVC\Applio-RVC-Fork\env\lib\site-packages\gradio\processing_utils.py", line 265, in move_files_to_cache return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj) File 
"C:\RVC\Applio-RVC-Fork\env\lib\site-packages\gradio_client\utils.py", line 919, in traverse return func(json_obj) File 
"C:\RVC\Applio-RVC-Fork\env\lib\site-packages\gradio\processing_utils.py", line 257, in _move_to_cache temp_file_path = move_resource_to_block_cache(payload.path, block) File 
"C:\RVC\Applio-RVC-Fork\env\lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache return block.move_resource_to_block_cache(url_or_file_path) File 
"C:\RVC\Applio-RVC-Fork\env\lib\site-packages\gradio\blocks.py", line 258, in move_resource_to_block_cache temp_file_path = processing_utils.save_file_to_cache( File 
"C:\RVC\Applio-RVC-Fork\env\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache temp_dir = hash_file(file_path) File 
"C:\RVC\Applio-RVC-Fork\env\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\RVC\\Applio-RVC-Fork\\assets\\audios\\v_output.wav'`

**Comment by sonphantrung** [comment] 2024-01-21 08:35
Mine works fine (from Colab)

**Comment by UnitedShoes** [comment] 2024-01-21 10:24
I am also having this exact issue. I tried removing the file name from the end of the Save location under Advanced, no luck. This traceback is from just launching Applio > Selecting model and audio > hitting convert 

`Traceback (most recent call last):
  File "C:\Users\Kyle\Desktop\Applio-3.0.3\env\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\Kyle\Desktop\Applio-3.0.3\env\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\Kyle\Desktop\Applio-3.0.3\env\lib\site-packages\gradio\blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\Kyle\Desktop\Applio-3.0.3\env\lib\site-packages\gradio\blocks.py", line 1456, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "C:\Users\Kyle\Desktop\Applio-3.0.3\env\lib\site-packages\gradio\processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "C:\Users\Kyle\Desktop\Applio-3.0.3\env\lib\site-packages\gradio_client\utils.py", line 919, in traverse
    return func(json_obj)
  File "C:\Users\Kyle\Desktop\Applio-3.0.3\env\lib\site-packages\gradio\processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "C:\Users\Kyle\Desktop\Applio-3.0.3\env\lib\site-packages\gradio\processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "C:\Users\Kyle\Desktop\Applio-3.0.3\env\lib\site-packages\gradio\blocks.py", line 258, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "C:\Users\Kyle\Desktop\Applio-3.0.3\env\lib\site-packages\gradio\processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "C:\Users\Kyle\Desktop\Applio-3.0.3\env\lib\site-packages\gradio\processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Kyle\\Desktop\\Applio-3.0.3\\assets\\audios'`

**Comment by aitronssesin** [comment] 2024-01-23 16:52
I this a current issue?

**Comment by MarcoReckless** [comment] 2024-01-24 11:08
> I this a current issue?

Yes, I did not have this issue on the versions before 3.0 but it persists through even the recent updates.

**Comment by aitronssesin** [comment] 2024-01-24 16:04
And you are sure you have the latest version and have you tried the precompiled?

**Comment by MarcoReckless** [comment] 2024-01-24 16:22
> And you are sure you have the latest version and have you tried the precompiled?

Yes, I do have the latest and this issue doesn't appear on the precompiled version.

**Comment by aitronssesin** [comment] 2024-01-24 16:32
So that's because you need to download the lastest source code zip from the releases because although the releases shows the version is the same, we update it.
![image](https://github.com/IAHispano/Applio/assets/74368135/81edacfa-7210-4aeb-815b-baf0de10c3c5)

**Comment by aitronssesin** [comment] 2024-01-24 16:33
But for now use the precompiled if that works for you

**Comment by MarcoReckless** [comment] 2024-01-24 18:02
After further testing, I noticed this still happens with longer audios, but the error is pretty much the same.

**Comment by aitronssesin** [comment] 2024-01-24 18:48
I tried with a 1 hour audio and there wasn't any error

**Comment by ChildLearningClub** [comment] 2024-01-25 05:27
I get this error on both the precompiled V3.0.3 and the and source V3.0.4.

**Comment by Keiser04** [comment] 2024-01-28 23:28
The same thing happens to me sometimes. Like right after uploading an audio and using it for example or using a new model.

**Comment by Anthonyxd22** [comment] 2024-01-29 08:23
a mi tambien me pasa ese mismo error

**Comment by Keiser04** [comment] 2024-01-29 14:43
> s\audios\v_output.wav' Traceback (most recent call last): File "C:\RVC\Applio-RVC-Fork\env\lib\site-packages\gradio\queueing.p

anthony calla

**Comment by Keiser04** [comment] 2024-01-31 14:27
He notado que en colab pasa mucho mas que en local

**Comment by RikeyLeKhey** [comment] 2024-01-31 19:20
Same problem here with the last update, i didn't have this problem before

**Comment by Puuuszzku** [comment] 2024-02-02 15:46
Same problem here on Ubuntu 23.10. I've tried versions tried 3.0.1 and 3.0.5.

**Comment by blaise-tk** [comment] 2024-02-29 14:03
In order to resolve this issue correctly it is important that you provide us with the exact steps you have performed, downloaded, compiled or github version... providing videos would be of great help, otherwise we will have to close the issue.

**Comment by Keiser04** [comment] 2024-02-29 14:48
> In order to resolve this issue correctly it is important that you provide us with the exact steps you have performed, downloaded, compiled or github version... providing videos would be of great help, otherwise we will have to close the issue.

en mi caso pasaba con la github version. si me vuelve a pasar lo grabo

**Comment by MarcoReckless** [comment] 2024-02-29 15:11
> In order to resolve this issue correctly it is important that you provide us with the exact steps you have performed, downloaded, compiled or github version... providing videos would be of great help, otherwise we will have to close the issue.

**1.** Everything left at default except for the Split Audio option.
**2.** If I split the audio via Applio it gives me the error, this doesn't happen if I don't.
**3.** This only seems to be an issue with long files, as I can split the audio just fine on shorter tracks.
**4.** I tried all of the recent versions, both precompiled and/or manually installed, though I don't think this makes a difference since plenty of other users reported the same issue; I always had this issue since the first 3.0 release.
**5.** I'm not really sure a video would change anything since all I get is an error log in the console.

**Comment by sanebg** [comment] 2024-02-29 17:36
The app is free and I still want my money back. 3 months the dev cannot resolve an issue. What a failure.

**Comment by blaise-tk** [comment] 2024-02-29 17:40
This error cannot be resolved as the error has not yet been replicated. Until someone shares an exhaustive description showing all the details it will be difficult to see what causes it.

**Comment by aitronssesin** [comment] 2024-02-29 17:50
> > In order to resolve this issue correctly it is important that you provide us with the exact steps you have performed, downloaded, compiled or github version... providing videos would be of great help, otherwise we will have to close the issue.
> 
> **1.** Everything left at default except for the Split Audio option. **2.** If I split the audio via Applio it gives me the error, this doesn't happen if I don't. **3.** This only seems to be an issue with long files, as I can split the audio just fine on shorter tracks. **4.** I tried all of the recent versions, both precompiled and/or manually installed, though I don't think this makes a difference since plenty of other users reported the same issue; I always had this issue since the first 3.0 release. **5.** I'm not really sure a video would change anything since all I get is an error log in the console.

We tried with "long files" as you said containing like 30 min - 1 hour and there wasn't any issue

**Closed** 2024-02-29 17:52 UTC
Labels: bug, help wanted, local

**Comment by albert-softie** [comment] 2024-03-04 01:28
i'm having the same issue on arch linux
this is the error log;
```bash
Traceback (most recent call last):
  File "/home/albert-softie/source/Applio-3.0.8/rvc/infer/infer.py", line 9, in <module>
    from pipeline import VC
  File "/home/albert-softie/source/Applio-3.0.8/rvc/infer/pipeline.py", line 17, in <module>
    from rvc.lib.FCPEF0Predictor import FCPEF0Predictor
  File "/home/albert-softie/source/Applio-3.0.8/rvc/lib/FCPEF0Predictor.py", line 18, in <module>
    from local_attention import LocalAttention
ModuleNotFoundError: No module named 'local_attention'
Traceback (most recent call last):
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1456, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio_client/utils.py", line 919, in traverse
    return func(json_obj)
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 258, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/albert-softie/source/Applio-3.0.8/assets/audios/CG5_-_BITE_OF_87_Main_Vocals_output.wav'
```

no output file is generated, using the patched fairseq as suggested earlier changed nothing, split audio makes no difference whether it's on or off, and the length/size of the input file seems to make no difference either. i'd be more than happy to provide any additional info if needed

**Comment by hienld92** [comment] 2024-03-08 02:10
I fixed this error by extract and replace all the file again, but if I press refresh the voice list button, this will happen again

**Comment by analytics-sinew** [comment] 2024-03-08 21:07
i had the same error and was unable to generate any audio file. I have replaced the output path for RVC Audio from "Applio-3.0.8\Applio-3.0.8\assets\audios\tts_rvc_output.wav" to "Applio-3.0.8\Applio-3.0.8\assets\audios\tts_output.wav".
Same as the output path for TTS audio and i was able to generate audio and dowload the file too.

Note : Im referring only for the TTS section of the tool

**Comment by RenamonAR** [comment] 2024-03-09 03:30
> i had the same error and was unable to generate any audio file. I have replaced the output path for RVC Audio from "Applio-3.0.8\Applio-3.0.8\assets\audios\tts_rvc_output.wav" to "Applio-3.0.8\Applio-3.0.8\assets\audios\tts_output.wav". Same as the output path for TTS audio and i was able to generate audio and dowload the file too.
> 
> Note : Im referring only for the TTS section of the tool

It worked perfectly!

**Comment by SpanishHearts** [comment] 2024-03-09 17:30
The last release is a total failure, broke a lot of things that worked perfectly fine the previous. I have no idea how an app can downgrade so much in a so little time. Even the 3.0.3 was awesome compared to the last couple of versions.

**Comment by blaise-tk** [comment] 2024-03-09 17:36
> The last release is a total failure, broke a lot of things that worked perfectly fine the previous. I have no idea how an app can downgrade so much in a so little time. Even the 3.0.3 was awesome compared to the last couple of versions.

ok bro

**Comment by albert-softie** [comment] 2024-03-09 17:48
> > i had the same error and was unable to generate any audio file. I have replaced the output path for RVC Audio from "Applio-3.0.8\Applio-3.0.8\assets\audios\tts_rvc_output.wav" to "Applio-3.0.8\Applio-3.0.8\assets\audios\tts_output.wav". Same as the output path for TTS audio and i was able to generate audio and dowload the file too.
> > Note : Im referring only for the TTS section of the tool
> 
> It worked perfectly!

well good for the both of you but the issue is specifically about inference being broken. this has nothing to do with the TTS component

**Comment by ZeusLT** [comment] 2024-03-09 22:11
In my case it works with some models but not the ones I trained on https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI. I get an error: `SynthesizerTrnMs768NSFsid.__init__() takes 19 positional arguments but 20 were given` 

```
Traceback (most recent call last):
  File "J:\Applications\AI\Voice\Applio\rvc\infer\infer.py", line 251, in <module>
    get_vc(model_path, 0)
  File "J:\Applications\AI\Voice\Applio\rvc\infer\infer.py", line 221, in get_vc
    net_g = SynthesizerTrnMs768NSFsid(*cpt["config"], is_half=config.is_half)
TypeError: SynthesizerTrnMs768NSFsid.__init__() takes 19 positional arguments but 20 were given
```


I did some debugging and found that the checkpoints that work sends these arguments (19): 
`[1025, 32, 192, 192, 768, 2, 6, 3, 0, '1', [3, 7, 11], [[1, 3, 5], [1, 3, 5], [1, 3, 5]], [12, 10, 2, 2], 512, [24, 20, 4, 4], 109, 256, 48000]`

the checkpoints that I trained and that don't work (20): 
`[1025, 32, 192, 192, 768, 2, 6, 3, 0, '1', [3, 7, 11], [[1, 3, 5], [1, 3, 5], [1, 3, 5]], [10, 10, 2, 2], 512, [16, 16, 4, 4], 109, 109, 768, 40000]`

and that is about where my investigation went a halt.

**Comment by albert-softie** [comment] 2024-03-10 02:35
i decided to try installing the local attention module that was mentioned in the original error (i tried installing it before posting in this thread but it didn't work because i didn't know the pip package was called `local-attention`, not `local_attention`) and all that changed is it gives a slightly different error now
```
/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Conversion completed. Output file: 'assets/audios/guys_what_one_is_your_favorite_Filtered_Vocals_MDX_v2_Voc_FT_output.wav' in 6.13 seconds.
Traceback (most recent call last):
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1456, in postprocess_data
    outputs_cached = processing_utils.move_files_to_cache(
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 265, in move_files_to_cache
    return client_utils.traverse(data, _move_to_cache, client_utils.is_file_obj)
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio_client/utils.py", line 919, in traverse
    return func(json_obj)
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 257, in _move_to_cache
    temp_file_path = move_resource_to_block_cache(payload.path, block)
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 234, in move_resource_to_block_cache
    return block.move_resource_to_block_cache(url_or_file_path)
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 258, in move_resource_to_block_cache
    temp_file_path = processing_utils.save_file_to_cache(
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 170, in save_file_to_cache
    temp_dir = hash_file(file_path)
  File "/home/albert-softie/source/Applio-3.0.8/.venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 102, in hash_file
    with open(file_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/albert-softie/source/Applio-3.0.8/assets/audios/guys_what_one_is_your_favorite_Filtered_Vocals_MDX_v2_Voc_FT_output.wav'
```
otherwise same end result as before, no output file is generated despite the log saying otherwise

**Comment by albert-softie** [comment] 2024-03-11 01:01
managed to figure it out with the help of someone from ai hub
basically; don't use the `run-install.sh` script on linux, it apparently somehow doesn't install all the requirements
instead if you want to install it you do
```
$ python3.10 -m venv .venv
$ source .venv/bin/activate
$ pip install -r requirements.txt
```

and then you can launch applio from the `run-applio` script. you may also need to set `TMPDIR` if you're having problems with building fairseq. no idea if any of this also applies to the windows script and/or how to fix it there if so

**Comment by McKaneCL** [comment] 2024-03-12 22:54
I Fixed it, reinstalling applio with "run-install.bat"
